### PR TITLE
Added support for Arch users

### PR DESCRIPTION
**Pull request by al-dot-exe**
Ran into connection issues on my Arch machine so I made a separate script. Only thing that's changed is `dpkg` commands are `pacman` commands.

### CODE REVIEW

**Comment by al-dot-exe** [comment]
Update: added the logic to determine which package manager is being used into the original file instead.

**Comment by shadow-absorber** [comment]
shadow has tested this commit and it works on their endeavour os install just fine... would try and get some others to test it if they have time just to see if this is a good addition

**Comment by CMNatic** [comment]
Hey @al-dot-exe thanks for the PR. I'm reviewing this :)

**Comment by AyhamAl-Ali** [comment]
Tested on ManjaroLinux (Arch based) and so far it works well
image
image

**Review by AyhamAl-Ali — APPROVED** [review]

**Comment by CMNatic** [comment]
PR approved. Thanks for the submission @al-dot-exe 

And to @shadow-absorber & @AyhamAl-Ali for the help in testing.

**Pull request merged**
