### PR TITLE
Translation into Russian

### PR DESCRIPTION
**Pull request by ghost**
Translation into Russian. File: README_RU.md

### CODE REVIEW

**Comment by ghost** [comment]
Translation into Russian

**Comment by CMNatic** [comment]
The translation looks good to me @MirniyVictor. I would suggest creating a new README.md to include the language rather than adding it to the README itself. For example, `README-RUS.md`

It would be good to add a section to the main `README.md` such as:

## Languages
- English - README.md
- Russian (Русский) - README-RUS.md

image

I have also added a [PR](https://github.com/tryhackme/openvpn-troubleshooting/pull/16) which adds support for Arch users. It'd be really useful if you wouldn't mind translating the [changes](https://github.com/tryhackme/openvpn-troubleshooting/pull/16/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) to the README.md (specifically line 14).

Thanks for the submission!

**Review by CMNatic — CHANGES_REQUESTED** [review]
Please see comments [here ](https://github.com/tryhackme/openvpn-troubleshooting/pull/11#issuecomment-1535527516)

**Comment by CMNatic** [comment]
Please ignore the above request. I can see you've done the changes I've requested already. PR merged 👍🏻

**Pull request merged**
